### ISSUE TITLE
Why all jobs are triggering despite using path filter? Explained and Resolved

### ISSUE THREAD

**Issue by TalhaNaeem101** [dorny/paths-filter#138]
I am using this filter for picking the changes in different microservices, it worked well while I tested on my public repo but the same CI file is not working for the private repo. Can you please confirm if it supports private repo CI or not?  A quick response will be highly appreciated. Thanks

**Comment by TalhaNaeem101** [comment]
@dorny

**Comment by TalhaNaeem101** [comment]
:)

**Comment by dorny** [comment]
Sorry @TalhaNaeem101, I get to reply on this quite late as I see. But I'm glad you have figured it out :)
So yes, It works in private repositories too. When I was developing it, I actually had a second private repo to test a "real" usage of the action.

**Comment by TalhaNaeem101** [comment]
Thanks @dorny . Your work is really awesome.
