### ISSUE TITLE
Action sometimes fails on push

### ISSUE THREAD

**Issue by GabriFila** [dorny/paths-filter#15]
Thanks a lot for this amazing action! We use it at [CrownLabs@Polito](https://github.com/netgroup-polito/CrownLabs)

We had some action ([1](https://github.com/netgroup-polito/CrownLabs/actions/runs/138739125), [2](https://github.com/netgroup-polito/CrownLabs/actions/runs/142462096)) failing on pushes, this is the log (same on both):
```
Run dorny/paths-filter@v2.0.0
  with:
    filters: webservice:
    - 'webservice/**/*'
  
    token: ***
/usr/bin/git fetch --depth=1 origin 0000000000000000000000000000000000000000
fatal: remote error: upload-pack: not our ref 0000000000000000000000000000000000000000
fatal: the remote end hung up unexpectedly
##[error]The process '/usr/bin/git' failed with exit code 128
```

[This](https://github.com/netgroup-polito/CrownLabs/blob/master/.github/workflows/webservice_lint_check.yml) is our action implementation. Can you tell us if we are doing something wrong

Thank you very much!

**Comment by dorny** [comment]
You're welcome :)

I can see the issue is here:
```
/usr/bin/git fetch --depth=1 origin 0000000000000000000000000000000000000000
```
Instead of those many zeroes there should have been SHA of the previous commit.
SHA is taken from the `before` field of the [push event payload](https://developer.github.com/webhooks/event-payloads/#push).

There must be some reason why Github provided this invalid SHA.
I can see your workflow is triggered on `push` but branches are not specified.
Could this be the case for the first push of a new branch?

I will look into it.

**Comment by GabriFila** [comment]
Yes, you are right it always happens on the first push of the new branch. If you need other info from us, feel free to ask

**Comment by chenlu-wang** [comment]
I have the same error for first push of new branches. Is it ok to use `ref` field instead `before` field to get SHA?  @dorny

**Comment by dorny** [comment]
To detect changed files we need a reference state (commit or branch) to which current state is compared to. For `pull_request`, the reference is obviously the target branch.

For `push` events, it could be either:

1. The last previously pushed commit **[current behavior]**
If there is no previously pushed commit then consider all files as changed **[not implemented yet]**

1. Top of the "base" branch. Base branch would be the repository default branch but it could be overridden using action input parameter. **[not implemented yet]**

So the issue with the current implementation is that there are no previously pushed commits for the new branches.

@chenlu-wang using `ref` would not help here. We would compare the latest commit on the branch to the top of the branch (same commit), so no changed would be detected.

I will add support for "base" branch soon.
It will basically make it work the same way as with opened pull request against the base branch, but without the PR itself.

Would this work for your use case?

**Comment by chenlu-wang** [comment]
@dorny Thanks for your explanation, it sounds sensible to compare to base branch as a reference state when there is no previous push commit, which should fix the issue in our case.

**Comment by GabriFila** [comment]
@dorny thanks for the explanation.

The behavior

> Top of the "base" branch. Base branch would be the repository default branch but it could be overridden using action input parameter. [not implemented yet]

would be great for us!

**Comment by Shatur95** [comment]
> Top of the "base" branch. Base branch would be the repository default branch but it could be overridden using action input parameter. [not implemented yet]

Same here. Would be nice to have.

**Comment by GabriFila** [comment]
This is great
Thank you very much!
