### ISSUE TITLE
Upgrade Action to use node 16 instead of node 12

### ISSUE THREAD

**Issue by ericcornelissen** [dorny/paths-filter#156]
Following the recent blog post ["GitHub Actions: All Actions will begin running on Node16 instead of Node12"](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) by GitHub, I noticed this action is still running on `node12`:

https://github.com/dorny/paths-filter/blob/8c7f485a57f7cad3483dcc0fdf36122a0542f200/action.yml#L50-L52

It should be fairly easy to change this by replacing `using: node12` with `using: node16` - I wouldn't expect anything in this Action's source code to break as a result of that.

One thing to note, by and large I've seen other Actions use a major version bump when releasing this change. The motivation being that older GitHub Actions runners may not support `node16`. See for example the ["What's new" section of `actions/checkout`](https://github.com/actions/checkout/tree/e6d535c99c374d0c3f6d8cd8086a57b43c6c700a#whats-new).

---

I noticed #151 includes this change. However, it's scope is quite broad which might be holding it back. Hence, I created this ticket to bring extra attention to this particular aspect of that PR.

**Comment by dorny** [comment]
Thanks for reporting the issue. The action was updated to use node16 in #161

**Comment by Anil1415** [comment]
I am getting an error that Node 12 deprecated while deploying through Azure github actions. 
I searched on internet and found out to update to Node 16
can anybody help me out.
