### ISSUE TITLE
Feature: Ability to print list of files created/updated/deleted

### ISSUE THREAD

**Issue by zenflow** [dorny/paths-filter#17]
First let me say THANK YOU for the awesome Action! I am already finding it extremely useful!

The proposal is to add the ability to print the list of files that were created/updated/deleted.

This would provide some transparency which can be helpful:
- when getting familiar with how dorny/paths-filter behaves
- when debugging a workflow

This could be done by default (my preference) or could be opt-in via a new input/option.

@dorny Would you be willing to review/merge a PR implementing this feature?

**Comment by dorny** [comment]
@zenflow Thanks for the suggestion.

Currently the action produces almost no information logs and very few [debug logs](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging)

If the `git diff-index` command is used, you can actually see list of changed files in the logs even now.
The `@actions/exec` package already logs all output from executed commands.
However unless you are already familiar with the implementation details of this action, the log is not much helpful.

Adding more transparency to the process is good idea. I totally agree with that.
I also agree that it should be done by default, without any input parameter.
PR improving this is welcome :)

However you mentioned: "created/updated/deleted".
I'm not sure if you meant it that way, but currently the action doesn't work with information whether file was actually created, updated or deleted.

Working with more detailed status information about changed files would open opportunities for some new features.
Originally this wasn't goal of this project but getting this information is easy and doesn't require any additional command or API request.
- [Pull Requests API](https://developer.github.com/v3/pulls/#list-pull-requests-files) has `status` field
- `git diff-index` has `--name-status` option

Those new features I'm thinking of would be more significant change and I would prefer to do some exploration on my own first.

So the conclusion:
If You are interested, please create a PR improving the transparency via better logging.
Meanwhile I will work or getting the more specific change status of each file and few new features using this information.
When both will be done, it could be published as a new release.

**Comment by dorny** [comment]
Implemented in release `v2.3.0`
