### ISSUE TITLE
Problem on detecting changes.

### ISSUE THREAD

**Issue by sonomirco** [dorny/paths-filter#172]
Hi there,
I have this warning running the action.
![image](https://user-images.githubusercontent.com/57708659/199405934-36df4044-2039-48e8-a8a3-276c904cfde3.png)

I cloned your action internally to my organization; otherwise, I wasn't allowed to run it.
I don't get why it is still listing all the files added in the first commit and not picking the last commits.

Any ideas?

**Comment by dorny** [comment]
@sonomirco can you post here a relevant part of your workflow? Which event triggers it and the paths-filter step?
