### ISSUE TITLE
Become 'Verified creator' on GitHub Marketplace

### ISSUE THREAD

**Issue by jtaylor-dohle** [dorny/paths-filter#202]
Would it be possible to become a verified creator on the GitHub marketplace?

It would be nice to allow only verified creator actions in my organisation repository:

![image](https://github.com/dorny/paths-filter/assets/125357469/d34896cd-286e-4179-8d08-2f53f5df21d4)

#### More information here:

https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-badges-in-github-marketplace

> Actions with the , or verified creator badge, indicate that GitHub has verified the creator of the action as a partner organization. Partners can email [partnerships@github.com](mailto:partnerships@github.com) to request the verified creator badge.

**Comment by dorny** [comment]
Hi @jtaylor-dohle,
I remember looking into this a few years back and it was available only for organizations, not individual users.
After a quick search, it seems nothing changed.

If you are sure I could get verified, please share how I should proceed and re-open the issue. Thanks.
