### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by darkxeno** [dorny/paths-filter#214]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dorny/paths-filter@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Thanks

**Comment by booleanbetrayal** [comment]
Looks like there is an open PR to fix this - https://github.com/dorny/paths-filter/pull/211

**Comment by darkxeno** [comment]
@dorny could you have a look at the linked PR.

Thanks

**Comment by darkxeno** [comment]
Following the thread i found the the version with commit id 8ec7be473424d724f09d3c51b7962ae5f2ffcbab
might be compatible with node 20 already.

**Comment by erikburt** [comment]
This action does run node20 if you point at HEAD - https://github.com/dorny/paths-filter/blob/master/action.yml#L51

Ideally a new tag/release is created so we can properly pin.

**Comment by dorny** [comment]
It's released now: [v2.12.0](https://github.com/dorny/paths-filter/releases/tag/v2.12.0)
I've also updated all dependencies.

@darkxeno please close this issue once you test the new version. Thanks.

**Comment by dorny** [comment]
Guys, yesterday I didn't realize bumping the Node version might be a breaking change.
I've deleted the `v2.12.0` and instead released it as [v3.0.0](https://github.com/dorny/paths-filter/releases/tag/v3.0.0).
I will leave `v2` pointing to the `v2.11.1` which is the last version on node16. 
From now on,  I will maintain a `v3` branch pointing to any future `v3.x.x` release.

**Comment by jsoref** [comment]
Yeah, it's definitely a breaking change for anyone using GHES or similar.

Thanks for splitting this off as v3.

**Comment by darkxeno** [comment]
Updated and working, thanks @dorny
