### ISSUE TITLE
Update major version tags to point to latest minor version commit when released

### ISSUE THREAD

**Issue by pavel-slama** [dorny/paths-filter#216]
Not a code issue, rather a release process suggestion.

e.g:
v2 -> v2.12.0 commit
after 2.13.0 release, update v2 -> v2.13.0 commit

That way worflows referring to major version as `dorny/paths-filter@v2` wouldn't have to update workflow files everytime a minor version is out and still get latest action code.

Minor versions shouldn't contain breaking changes anyway and workflows can still use v2.0.0 or commit hash if they for some reason require original v2 commit.

**Comment by dorny** [comment]
Yeah, that's exactly what I have been doing from the beginning. I just forgot to update v2 yesterday, thanks for pointing this out. However, it's probably better I forgot to do it. The latest version updated the Node version from 16 to 20. This might be a breaking change. I will release it as `3.0.0` instead

**Comment by dorny** [comment]
Released as [v3.0.0](https://github.com/dorny/paths-filter/releases/tag/v3.0.0) and I will maintain also a `v3` branch pointing to any future `v3.x.x` release. I will leave `v2` pointing to the `v2.11.1` which is the last version on node16
