### ISSUE TITLE
Create a major version tag

### ISSUE THREAD

**Issue by jadchaar** [dorny/paths-filter#34]
Would it be possible to create a major version tag that constantly gets updated with each minor version like in actions/checkout: https://github.com/actions/checkout/releases? This would allow us to reference this action by just doing `uses: dorny/paths-filter@v2` in our workflow YML files since it is a bit of a pain to constantly keep up with each minor version release.

**Comment by dorny** [comment]
I've created tag `v2`.
Sorry for the inconvenience :)

**Comment by jadchaar** [comment]
> I've created tag `v2`.
> Sorry for the inconvenience :)

Thanks a ton, it works great! Thanks for the awesome action!
