### ISSUE TITLE
Git error 129 while searching for merge-base with master

### ISSUE THREAD

**Issue by avolusb** [dorny/paths-filter#41]
Hello, first of all, i grateful for developing this action. I have a problem, im trying to use this action in my workflow, but have an error during step "Searching for merge-base with master" immediately after launch build. I started build from my branch, and need to know, does files in my branch after commit different than files in master. Look at screenshot, git is cant find command like "no-auto-gc", maybe you see this error before and know how to fix it? 
P.S. Builds without this action working good.
P.S.S. And i cant find any information about this command. 

![Screenshot_8](https://user-images.githubusercontent.com/72386867/95177075-6b4c1780-07c6-11eb-994a-d55a5c5055a8.png)

**Comment by dorny** [comment]
Hello,
It invokes command `git fetch` with option flag [`--no-auto-gc`](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---no-auto-gc)
This flag is basically just an unnecessary micro-optimization which prevents running git garbage collection in your git repository after data are fetched from remote.

This option is relatively new, it was added in git version 2.23. Looks like your runner has older git version. Are you using Github provided runner or self-hosted?
It worked fine on Github ubuntu-latest runner. Maybe the windows runner are using older version of git.

Anyway, I will asap release new version where this option won't be used.

**Comment by avolusb** [comment]
Thank you for answer me, i use self-hosted runner.
 Yeah, my machine using older git version, and this option is not available for me. 

> Anyway, I will asap release new version where this option won't be used.

Thank you very much, this will help me a lot

**Comment by dorny** [comment]
@avolusb: Does it work for you now?
I'm just checking if there are no other issues on self-hosted windows runners as I didn't test this setup at all.
Thanks

**Comment by avolusb** [comment]
Yes, its worked. Thank you for fast response to this issue.
