### ISSUE TITLE
Are filters `AND`ed?

### ISSUE THREAD

**Issue by billyvg** [dorny/paths-filter#45]
Hey, great work on this, I see you've discovered our usage of it at Sentry. We're trying to use a few negation filters together, as an example

```yaml
backend:
  - '!**/*.tsx'
  - '!**/*.less'
```

However, this doesn't work as I had expected - it seems to be `OR`ing each filter so if I had a commit where a `tsx` file changed, `backend` would still match due to the second filter. Is this expected? Am I writing the filters incorrectly?

**Comment by dorny** [comment]
Yeah I got notification that @getsentry forked the repo. Then I got an idea I could use it as a "real world" usage example in successful project :)

Your findings are correct. Filter evaluates to true if any of the path patterns matches any file - so it's `OR`.
Solution would be to merge it into one negated pattern:
```
backend:
  - '!(**/*.tsx|**/*.less)'
```

Unfortunately I found out [minimatch](https://github.com/isaacs/minimatch) library is not handling this correctly.
I quickly tested it with [micromatch](https://github.com/micromatch/micromatch) and that seems to work.

`micromatch` claims to support full Bash 4.3 spec and it actually passes all the tests so using it seems to be a good improvement anyway. I will release new version with micromatch in following days and then the `'!(**/*.tsx|**/*.less)'` pattern should work.
