### ISSUE TITLE
Support workflow_dispatch event

### ISSUE THREAD

**Issue by Cyberbeni** [dorny/paths-filter#52]
When I start my workflow manually with workflow_dispatch, I get the following warning and changes will be detected even though there wasn't any: `'before' field is missing in PUSH event payload - changes will be detected from last commit`

Run: https://github.com/Cyberbeni/install-swift-tool/runs/1432414699?check_suite_focus=true
Workflow: https://github.com/Cyberbeni/install-swift-tool/blob/70b350e0cafa467112631131ea9e64dc29f979b0/.github/workflows/update-dependencies.yml
Commit created because changes in 'dist/**' were detected: https://github.com/Cyberbeni/install-swift-tool/commit/a68d9a3f310d6715038bdf1a4eea62d3622b2fb6

**Comment by Cyberbeni** [comment]
Ah, now I realised that this action is supposed to check for changes for the previous commit or the pull request and not local changes.

**Comment by dorny** [comment]
With some small changes I could make it work with local changes too. Could you please shortly describe your use case?

**Comment by Cyberbeni** [comment]
I managed to solve my issue with a simple run phase:
```
    - name: Detect changes in distributed code
      if: ${{ github.event.inputs.force != 'true' }}
      id: changes
      run: |
        if [[ $(git status --porcelain ./dist) != "" ]]; then
          echo "::set-output name=dist::true"
        fi
```

I have a workflow that updates dependencies for my GitHub Action but only creates a pull request if the distributed code changed or the force input was set to true. (In case there is a security vulnerability in one of the development dependencies) This workflow also runs weekly with a cron trigger.

**Comment by dorny** [comment]
Detecting local changes is pretty easy. Usually there's no real need for a 3rd party action as you already figured out. Anyway supporting this will require just a cosmetic changes to what I have already so I will add it in next days.

Thanks for the idea 👍
