### ISSUE TITLE
[Feature] unquoted list of files

### ISSUE THREAD

**Issue by s0undt3ch** [dorny/paths-filter#54]
Would it be possible to add the possibility to have  the list of files, shell escaped, but unquoted?

**Comment by dorny** [comment]
Yes, should be doable. I just have to double-check escaping rules to ensure correct behavior. I will look into it in few days.

**Comment by s0undt3ch** [comment]
I managed to get what I needed by using

`${{ join(fromJSON(your-action-json-output), ' ')`

So maybe a FAQ or example is all that is needed.

**Comment by dorny** [comment]
Glad to see you found a solution that works for you. 

For most cases this should be fine, however there is no shell escaping applied so some obscure file name could break one's pipeline.  After very quick research it looks that it should be safe to backslash escape everything except `[a-zA-Z0-9_/.]`. It should keep normal filenames without any change while still behave correctly in all cases. I will keep it on my todolist.

By the way, I'm quite curious. Why do you need shell escaped, but without quotes?

**Comment by s0undt3ch** [comment]
I'm feeding those files to another tool, pre-commit, which is not expecting them to be quoted
