### ISSUE TITLE
Ignoring some subfolders from filter

### ISSUE THREAD

**Issue by avolusb** [dorny/paths-filter#56]
Hello, 
Thank you for developing this great tool, it very helpful in my current project.
But I have a little problem, I can't ignore folders which contain other folders, maybe your tool have some option to ignore folders from filter?
I mean a situation when folder system looks like:
Folder1:
   Folder11
   Folder12
   Folder13

And I want to ignore for example Folder 12, but checking Folder13 and Folder11, maybe you know some solution for that case? 

P.S. I'm trying to use 'ignore' option from micromath  - '(BigFolder/**, {ignore: InsideFolder})', but it not works, filter just disabled and don't see any file changes :(

**Comment by dorny** [comment]
Hello,

It should work this way: `BigFolder/!(InsideFolder/**)/**`
This will match everything inside *BigFolder* except all files under *InsideFolder* folder.
Please confirm if it works for you by closing this issue. Staring the repo will be also appreciated :)

P.S.: You can't use `{ignore: InsideFolder}` - this would have to be added to second argument when this action invokes the `picomatch(glob, options)`. Using this action whatever you write inside filter will be used as the first glob argument.

**Comment by avolusb** [comment]
Thank you for fast answer.
Great, this solved one part of my problem, the second part is: what I need to do if I want to ignore couple folders inside big folder? 
Am I need to create one more filter? Or it function can take multiple arguments?

**Comment by dorny** [comment]
If you want to ignore multiple folders inside the `BigFolder` you can use this:
`BigFolder/!((InsideFolder|IgnoreThisToo)/**)/**`
This will match everything inside *BigFolder* except files under *InsideFolder* and *IgnoreThisToo* folders.

If there would be too many folders to ignore it could be easier to switch to "whitelist" and explicitly lists folders you are interested in.

If you are not sure how the matching will behave I would suggest you to clone this repo and look into `__tests__/filter.test.ts`. It's quite easy to modify and run tests to see what would happen in some specific case. That's actually exactly what I did now.

**Comment by avolusb** [comment]
Yes, this solve all my problems, thank you very much for your help, happy new year!

**Comment by jawahar-integrate** [comment]
Hi ,

I need help in ignoring the file , which is not actual ignore . I have two different work flows like metioned below structure ,

work_flow_A
   src (with in work_flow_A. "dir")
      file-1
      flie-2 
      file -3
   package.json (with in src dir)
src (top level dir)
  file-1
  file-2
package.json (top level dir)

jobs:
  changes_detection:
    runs-on: 
    
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          run_work_flow_A:
           - 'work_flow_A/**'
           - '!src/**'
           - '!package.json'
          run_work_flow_b:
           - '!work_flow_A/**'

the work flow A should true when there is change in workflowA dir and it shoudl ignore  if there is change in top level sc dir and in top level package.json file .

The workflow B should true when there is change in entire foler structure except the work_flow_A. 


could you please help me in setting up these filters

**Comment by xiaxuchen** [comment]
The following example demonstrates how to exclude specific subfolders in a workflow configuration:
```
jobs:
  paths-filter:
    runs-on: ubuntu-22.04
    outputs:
      test_ci: ${{ steps.filter.outputs.test_ci }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            test_ci:
              - 'test/!(test-frontend-next|test-frontend)/**'
```
With this setup, the `test_ci` output will be set to true if there are changes within the `test` directory, excluding any changes made specifically in the `test/test-frontend-next` or `test/test-frontend` subdirectories. This allows for targeted CI runs that only trigger when relevant files are modified
