### ISSUE TITLE
Add counts to output?

### ISSUE THREAD

**Issue by billyvg** [dorny/paths-filter#63]
So one of the ways we're using this is to find added/modified files to pass to our linter. We use `          list-files: shell` since we pass this list of files to the linter. However, we'd also like to get the count of files so that we can do some different conditionals based on the # of changed files.

Any objections to adding the count to the action outputs?

**Comment by dorny** [comment]
If there is use-case for it then why not. I will add it later today.
We already have `${FILTER_NAME}_files` so this could be `${FILTER_NAME}_count` or something like that.

**Comment by billyvg** [comment]
Thank you once again!
