### ISSUE TITLE
Support comma separated list-files enum

### ISSUE THREAD

**Issue by paulius-p** [dorny/paths-filter#67]
There are quite a few cases were you need to provide a comma separated list of files for cli arguments or properties. So I think it would be good to be able to define it in the action, rather that doing sed.

**Comment by dorny** [comment]
Good idea. There's not much work to implement it. I will add it soon 👍

**Comment by dorny** [comment]
Actually there's an easy way how to do it in current version.

Use `list-files: json` and afterwards you can get coma separated list like this:
 `join(fromJSON(steps.filter.outputs.FILTER_NAME_files))`

 `list-files: json` - enables file listing using JSON format, still every action output is just a string
`fromJSON()` - will parse that string into actual JSON array
[ `join`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#join) - will concatenate array using default separator `,`

Does it work for you or is there anything missing?

**Comment by paulius-p** [comment]
Sure, that's a possible workaround, though I think it would be much cleaner and less verbose if there would be an option in the action. Though it's up to you :)
