### ISSUE TITLE
Github API reports 0 files changed on merge to main

### ISSUE THREAD

**Issue by sam-hoffman** [dorny/paths-filter#81]
We have separate `main` and `develop` branches, and merge to main intermittently. On all merges to `develop`, the Github API reported changed files and the paths filter worked great.

On the merge to main, even though the PR page said 280 files were changed, the output from the paths filter said none were changed: 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/33353348/114211974-871faa00-991e-11eb-901f-d17126b13b15.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/33353348/114212023-943c9900-991e-11eb-9e2d-6e109092c211.png">

Ideally, I'd like these changed files to trigger tests. Any thoughts on what's going on here?

**Comment by dorny** [comment]
Seems like a bug or some strange undocumented behavior on GitHub side.
This happened only once or every time you try to merge to main?
The `0` from `Number of changed_files is 0` log line is taken directly from action event payload: `github.context.payload.pull_request.changed_files`

I'm using this number as limit in `for` loop while fetching files from API.
I could change it so it will always try to fetch files and will stop only if there are no more new files.
I'm not so happy about it - respecting the `changed_files` field feels like a proper implementation but who knows what's actually happening on GitHub side.

**Comment by sam-hoffman** [comment]
We've only tried to merge to `main` once since I've added your filter to our PR tests (as you can see from the number of commits and files changed, lol)

I did try re-running the action but got the same outcome.

**Comment by dorny** [comment]
Should be now fixed in versions `v2`  and `v2.10.0`.
If it still doesn't work for you please let me know and reopen this issue.

**Comment by sam-hoffman** [comment]
It worked! Thank you so much :)
