### ISSUE TITLE
Pull Request changes should only consider latest pushed changes

### ISSUE THREAD

**Issue by mccare** [dorny/paths-filter#96]
Right now when filtering inside a pull_request workflow, the list of changes will be all changes inside the pull request. 

Ideally the filter would run only on the changes that have been made between the last push to the PR and the current push to the PR. I'm aware that rebaseing and force pushing will screw things up (I would then take the whole changeset of the PR as filter). But for small changes to the PR, I don't want to trigger all builds of all components if only one is affected.

Is there a way to do this already?

Christian

**Comment by dorny** [comment]
What you described, is exactly how it works when the action is triggered by `push` events and the base is configured to be the same branch as it was pushed to.

Event data of `push` event has `before` field providing the SHA of last previously pushed commit. I'm not sure if there is such a field in event of PR update. If yes, then the behavior you described should be in theory possible to implement. An alternative would be to run the workflow on each push to a feature branch, maybe combined with some other filter to do it only when there is an rPR.

To be completely honest, I don't plan to implement anything to make this possible. I simply don't have enough time. If that feature would be really useful for you, I would suggest to fork this repo and use it as a base for your own implementation.
