### ISSUE TITLE
Problem using with pull_request trigger

### ISSUE THREAD

**Issue by mike-potter** [dorny/paths-filter#99]
When triggered via pull_request, the paths-filter always compares against the base branch for the PR. While this is fine for the first push, on subsequent pushes to the same PR it ignores the "base" option so it will always detect the same file changes, rather than just the most recent changes.

In our workflow, we provision a cloud environment when a PR is created.  When there is a "synchronize" event from a later commit/push we don't want to re-provision the environment unless the kubernetes config files have changed.

Right now, paths-filter always detects the change and re-provisions on each commit/push.  If I try switching from a pull_request trigger to a push trigger then it only sees the change in the latest commit rather than the last pushed commit (gitlab only has the gitlab.payload.before defined for pull requests)

Is there any way to allow the "base" option to be respected for pull_request triggers so we can point to the gitlab.payload.before instead of always using the base branch of the PR?

**Comment by dorny** [comment]
There was a similar request two weeks ago #96 
I understand your use case, but unfortunately, I don't have any spare time now to work on it. At least not in the near future.
You can always fork this repo and try to implement it on your own :)
